# NEURAL NETWORK SIZES
EMB_SZS = [(13, 7), (6, 3), (5, 3)]
CONTINUOUS = 4
BINARIES = 10
# NEURAL NETWORL ARCHITECTURE
LAYERS = [100,200,100]
OUTPUT = 1
# NEURAL NETWORL PARAMETERS
DROPOUT = 0.4
# THRESHOLD VALUE
THRESHOLD_VALUE = 0.2
# URL MODEL
MODEL_FILE = "IA_Model/saving_models/CardioDisease_1output.pt"
