# Connection with telegram bot
TOKEN = "6528849543:AAH20UNoXaWelPcvEKZEd75k8SYU_N7Vjk4"

# Data requiere to do a diagnostic
START, \
GENDER, \
PREGNANT, \
PREGNANCYWEEKS, \
AGE, \
WEIGHT, \
HEIGHT, \
BMI, \
RACE, \
SMOKE, \
DRINK, \
EXERCISE, \
SLEEPTIME, \
PHYSICALHEALTH, \
MENTALHEALTH, \
DIFWALKING, \
GENHEALTH, \
STROKE, \
ASTHMA, \
DIABETIS, \
KIDNEYDISEASE,\
SKINCANCER = range(22)